name: Sincronizar con Hugging Face Spaces

on:
  push:
    branches:
      - main
      - web-deploy
  # Permite correr esta acción manualmente desde GitHub
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Empujar a Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          echo "dataset_obb/" >> .gitignore
          echo "runs/" >> .gitignore
          echo "*.ipynb" >> .gitignore
          echo "*.jpg" >> .gitignore
          echo "*.png" >> .gitignore
          echo "*.pdf" >> .gitignore
          git lfs install
          git lfs track "*.mp4" "*.pt"
          git add .
          git add -f runs/obb/runs/tenis_mesa_obb_run/weights/best.pt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit -m "Deploy to Hugging Face"
          git push https://agustinah:$HF_TOKEN@huggingface.co/spaces/agustinah/table-tennis-cv HEAD:main -f
